export const FETCH_MOVIE_PENDING = 'FETCH_MOVIE_PENDING';
export const FETCH_MOVIE_FULFILLED = 'FETCH_MOVIE_FULFILLED';
export const FETCH_MOVIE_REJECTED = 'FETCH_MOVIE_REJECTED';

export const FETCH_MOVIES_PENDING = 'FETCH_MOVIES_PENDING';
export const FETCH_MOVIES_FULFILLED = 'FETCH_MOVIES_FULFILLED';
export const FETCH_MOVIES_REJECTED = 'FETCH_MOVIES_REJECTED';

export const ADD_MOVIE_PENDING = 'ADD_MOVIE_PENDING';
export const ADD_MOVIE_FULFILLED = 'ADD_MOVIE_FULFILLED';
export const ADD_MOVIE_REJECTED = 'ADD_MOVIE_REJECTED';

export const UPDATE_MOVIE_PENDING = 'UPDATE_MOVIE_PENDING';
export const UPDATE_MOVIE_FULFILLED = 'UPDATE_MOVIE_FULFILLED';
export const UPDATE_MOVIE_REJECTED = 'UPDATE_MOVIE_REJECTED';

export const DELETE_MOVIE_PENDING = 'DELETE_MOVIE_PENDING';
export const DELETE_MOVIE_FULFILLED = 'DELETE_MOVIE_FULFILLED';
export const DELETE_MOVIE_REJECTED = 'DELETE_MOVIE_REJECTED';
